### ISSUE TITLE
Issue setting up ICS2000 integration - 

### ISSUE THREAD

**Issue by JesperVerschoor** [rdegraafwhizzkit/ics2000-hass#5]
I've followed the provided steps and after restarting my HA, I've found no entities loaded and the below log statement. It seems to have issues pulling the devices from KAKU. Any idea or tips?

``Logger: homeassistant.components.light
Source: custom_components/ics2000/light.py:55
Integration: Light ([documentation](https://www.home-assistant.io/integrations/light), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+light%22))
First occurred: 2:46:15 PM (1 occurrences)
Last logged: 2:46:15 PM

Error while setting up ics2000 platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 353, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ics2000/light.py", line 55, in setup_platform
    hub = Hub(
          ^^^^
  File "/usr/local/lib/python3.11/site-packages/ics2000/Core.py", line 38, in __init__
    self.pull_devices()
  File "/usr/local/lib/python3.11/site-packages/ics2000/Core.py", line 70, in pull_devices
    decrypted = json.loads(decrypt(device["data"], self.aes))
                                   ~~~~~~^^^^^^^^
TypeError: string indices must be integers, not 'str'``

**Comment by rdegraafwhizzkit** [comment]
You may add a code line like '		logging.info(resp)' (note the spaces) after line 67 in ics2000/Core.py and send me the logging again.
